version: "3"

volumes:
  sqlite: {}
  sqlite-backup: {}

networks:
  default:
    name: manga_network

services:
  django: &django
    build:
      context: ./
      dockerfile: ./compose/local/django/Dockerfile
    image: kindlemanga_django
    container_name: kindlemanga_django_local
    depends_on:
      - redis
    volumes:
      - ./manga_web:/app:z
      - ./manga_crawler:/crawler:z
      - sqlite:/app/kindle_manga.db:z
      - ~/.aws/:/root/.aws:ro
    env_file:
      - ./.envs/.local/.django
    ports:
      - "8000:8000"
    command: /start

  celeryworker:
    <<: *django
    image: manga_local_celeryworker
    container_name: manga_local_celeryworker
    depends_on:
      - redis
    ports: []
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: manga_local_celerybeat
    container_name: manga_local_celerybeat
    depends_on:
      - redis
    ports: []
    command: /start-celerybeat

  flower:
    <<: *django
    image: manga_local_flower
    container_name: manga_local_flower
    ports:
      - "5555:5555"
    command: /start-flower

  redis:
    image: redis:6
    container_name: manga_redis_local
    expose:
      - 6379

  splash:
    image: scrapinghub/splash
    container_name: manga_splash_local
    expose:
      - 8050
