version: "3"

networks:
  default:
    name: manga_network

services:
  django: &django
    build:
      context: ./
      dockerfile: ./compose/production/django/Dockerfile
    image: kindlemanga_django
    container_name: kindlemanga_django_production
    depends_on:
      - redis
    volumes:
      - ./manga_web:/app:z
      - ./manga_crawler:/crawler:z
      - ~/.aws/:/root/.aws:ro
    env_file:
      - ./.envs/.production/.django
    ports:
      - "8086:8080"
    command: /start

  celeryworker:
    <<: *django
    image: manga_production_celeryworker
    container_name: manga_production_celeryworker
    depends_on:
      - redis
    ports: []
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: manga_production_celerybeat
    container_name: manga_production_celerybeat
    depends_on:
      - redis
    ports: []
    command: /start-celerybeat

  flower:
    <<: *django
    image: manga_production_flower
    container_name: manga_production_flower
    ports:
      - "5555:5555"
    command: /start-flower

  redis:
    image: redis:6
    container_name: manga_redis_production
    expose:
      - 6379

  splash:
    image: scrapinghub/splash
    container_name: manga_splash_local
    expose:
      - 8050
