# Generated by Django 2.0.4 on 2018-04-08 03:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manga", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Chapter",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("source", models.URLField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name="volume",
            name="chapters",
        ),
        migrations.AlterField(
            model_name="volume",
            name="download_link",
            field=models.URLField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="chapter",
            name="volume",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="manga.Volume"
            ),
        ),
    ]
