# Generated by Django 2.0.4 on 2018-04-08 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0002_auto_20180408_0328'),
    ]

    operations = [
        migrations.AddField(
            model_name='volume',
            name='number',
            field=models.IntegerField(null=True),
        ),
    ]
