# Generated by Django 2.0.4 on 2018-04-08 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manga", "0003_volume_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chapter",
            name="source",
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name="manga",
            name="image_src",
            field=models.URLField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="manga",
            name="source",
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name="volume",
            name="download_link",
            field=models.URLField(max_length=500, null=True),
        ),
    ]
