# Generated by Django 2.0.4 on 2018-04-09 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manga", "0004_auto_20180408_0558"),
    ]

    operations = [
        migrations.AddField(
            model_name="manga",
            name="description",
            field=models.TextField(null=True),
        ),
    ]
