# Generated by Django 2.0.2 on 2018-05-23 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0005_manga_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manga',
            name='name',
            field=models.CharField(max_length=500),
        ),
    ]
