# Generated by Django 2.0.8 on 2018-12-28 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0009_manga_full'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manga',
            name='source',
            field=models.URLField(max_length=5000),
        ),
    ]
