# Generated by Django 2.0.8 on 2018-12-28 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manga", "0011_auto_20181228_1106"),
    ]

    operations = [
        migrations.AlterField(
            model_name="manga",
            name="name",
            field=models.TextField(),
        ),
    ]
