# Generated by Django 2.0.8 on 2018-12-28 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0012_auto_20181228_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manga',
            name='web_source',
            field=models.CharField(choices=[('blogtruyen', 'blogtruyen'), ('nettruyen', 'nettruyen'), ('mangaseeonline', 'mangaseeonline')], max_length=200),
        ),
    ]
