# Generated by Django 4.0.5 on 2022-06-05 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0015_auto_20181228_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='manga',
            name='unicode_name',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='manga',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='volume',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
