# Generated by Django 4.0.5 on 2022-06-05 15:59

from django.db import migrations, models
import manga.models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0016_manga_unicode_name_alter_chapter_id_alter_manga_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volume',
            name='download_link',
        ),
        migrations.RemoveField(
            model_name='volume',
            name='fshare_link',
        ),
        migrations.AddField(
            model_name='chapter',
            name='number',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='volume',
            name='file',
            field=models.FileField(null=True, upload_to=manga.models.manga_directory_path),
        ),
    ]
