#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

# runserver if DEBUG else gunicorn
if [ "$DEBUG" = "True" ]; then
  CMD="python manage.py runserver 0.0.0.0:8000"
else
  CMD="gunicorn --bind 0.0.0.0:8080 --workers 3 --access-logfile - --error-logfile - --log-level info main.wsgi:application"
fi

# if the db file doesn't exist we get it from the REPLICA_URL
[ ! -f $DB_FILE ] && litestream restore -v -if-replica-exists -o $DB_FILE "${REPLICA_URL}" \
  ; python manage.py migrate \
  ; python manage.py collectstatic --no-input \
  ; litestream replicate -exec "${CMD}" $DB_FILE "${REPLICA_URL}"
