environment:
  PYTHON: "C:\\Python37-x64"

install:
  - set PATH="%PYTHON%\\Scripts";%PATH%
  - "%PYTHON%\\python.exe -m pip install --upgrade pip setuptools wheel"
  - "%PYTHON%\\python.exe -m pip install -r requirements.txt"
  - "%PYTHON%\\python.exe -m pip install certifi https://github.com/pyinstaller/pyinstaller/archive/develop.zip"

build_script:
    - "%PYTHON%\\python.exe setup.py build_binary"

artifacts:
  - path: dist\KCC*
